# Generated by Django 3.1.12 on 2026-01-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteees', '0003_delete_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
