# Generated by Django 3.1.12 on 2026-01-08 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteees', '0004_reviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reviews',
        ),
    ]
