# Generated by Django 3.1.12 on 2026-01-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteees', '0005_delete_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='comment',
            field=models.TextField(default='fg'),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(default='4'),
        ),
    ]
