# Generated by Django 3.1.12 on 2026-01-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteees', '0006_auto_20260108_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('movie_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
    ]
